/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import app.bolivia.swing.JCTextField;
import controllers.BookController;
import controllers.IssueController;
import controllers.StudentController;
import java.awt.Color;
import utils.DBConnection;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JFrame;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import models.Book.Book;
import models.Student.Student;

/**
 *
 * @author trinh
 */
public class IssueBook extends javax.swing.JFrame {

    private StudentController studentController;
    private BookController bookController;
    private IssueController issueController;

    /**
     * Creates new form IsssueBook
     */
    public IssueBook() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        studentController = new StudentController(this);
        bookController = new BookController(this);
        issueController = new IssueController(this);
        setMajorsToComboBox();
        setDate();
    }

    public void setMajorsToComboBox() {
        for (String major : studentController.getAllMajors()) {
            comboBoxMajor.addItem(major);
        }
    }

    public void setDate() {
        date_issueDate.setFormatoFecha("dd/MM/yyyy");
        date_dueDate.setFormatoFecha("dd/MM/yyyy");

        date_issueDate.setDatoFecha(new Date());

        Date currentDate = new Date();

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        calendar.add(Calendar.DAY_OF_YEAR, 90);

        Date newDate = calendar.getTime();

        date_dueDate.setDatoFecha(newDate);

    }

    public boolean validateUserInput() {
        if (txt_studentId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên");
            return false;
        }

        try {
            int id = Integer.parseInt(txt_studentId.getText());
            Student student = studentController.getStudentById(id);
            if (student != null) {
                lbl_studentId.setText(String.valueOf(student.getId()));
                lbl_studentName.setText(student.getName());
                lbl_email.setText(student.getEmail());
                comboBoxMajor.setSelectedItem(student.getMajor());
            } else {
                JOptionPane.showMessageDialog(this, "Sinh viên không tồn tại");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã sinh viên không hợp lệ");
            return false;
        }

        if (txt_bookId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách");
            return false;
        }

        Book book = bookController.getBookById(txt_bookId.getText());
        if (book != null) {
            lbl_bookId.setText(book.getId());
            lbl_bookName.setText(book.getTitle());
            lbl_author.setText(book.getAuthor());
            lbl_category.setText(book.getGenre());
            lbl_publisher.setText(book.getPublisher());
            lbl_quantity.setText(String.valueOf(book.getQuantity()));
        } else {
            JOptionPane.showMessageDialog(this, "Sách không tồn tại");
        }

        if (isAlreadyIssued()) {
            JOptionPane.showMessageDialog(this, "Bạn đã mượn quyển sách này");
            return false;
        }

        if (Integer.parseInt(lbl_quantity.getText()) == 0) {
            JOptionPane.showMessageDialog(this, "Sách này tạm thời hết");
            return false;
        }
        return true;
    }

//    Check if a book is already issued by a student
    public boolean isAlreadyIssued() {
        String bookId = txt_bookId.getText();
        int studentId = Integer.parseInt(txt_studentId.getText());

        if (issueController.getByBookIdAndStudentId(bookId, studentId) != null) {
            return true;
        }

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSDateChooserBeanInfo1 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        panel_main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_studentId = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl_studentName = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_email = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        comboBoxMajor = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_bookId = new app.bolivia.swing.JCTextField();
        txt_studentId = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        date_issueDate = new rojeru_san.componentes.RSDateChooser();
        date_dueDate = new rojeru_san.componentes.RSDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        submitButton = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_bookId = new app.bolivia.swing.JCTextField();
        jLabel21 = new javax.swing.JLabel();
        lbl_bookName = new app.bolivia.swing.JCTextField();
        jLabel22 = new javax.swing.JLabel();
        lbl_author = new app.bolivia.swing.JCTextField();
        lbl_publisher = new app.bolivia.swing.JCTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_category = new app.bolivia.swing.JCTextField();
        jLabel25 = new javax.swing.JLabel();
        lbl_quantity = new app.bolivia.swing.JCTextField();
        lbl_bookError = new javax.swing.JLabel();
        lbl_studetntError = new javax.swing.JLabel();
        checkButton = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MSSV");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        lbl_studentId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_studentIdActionPerformed(evt);
            }
        });
        jPanel1.add(lbl_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 340, 40));

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Họ và tên");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, -1));

        lbl_studentName.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_studentNameActionPerformed(evt);
            }
        });
        jPanel1.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 40));

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        lbl_email.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_emailActionPerformed(evt);
            }
        });
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 340, 40));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Thông tin sinh viên");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        comboBoxMajor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMajorActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 340, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/51516_arrow_back_left_icon.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Khoa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, -1));

        panel_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 800));

        jLabel15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("Mã sách");
        panel_main.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 80, -1));

        txt_bookId.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 112, 192), null));
        txt_bookId.setForeground(new java.awt.Color(102, 102, 102));
        txt_bookId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_bookId.setPhColor(new java.awt.Color(102, 102, 102));
        txt_bookId.setPlaceholder("Nhập mã sách");
        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusLost(evt);
            }
        });
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 240, 40));

        txt_studentId.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 112, 192), null));
        txt_studentId.setForeground(new java.awt.Color(102, 102, 102));
        txt_studentId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_studentId.setPhColor(new java.awt.Color(102, 102, 102));
        txt_studentId.setPlaceholder("Nhập mã sinh viên");
        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusLost(evt);
            }
        });
        txt_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 240, 40));

        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 204));
        jLabel16.setText("Ngày trả");
        panel_main.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 90, -1));

        date_issueDate.setEnabled(false);
        date_issueDate.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        date_issueDate.setFuente(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        date_issueDate.setPlaceholder("Chọn ngày mượn");
        panel_main.add(date_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, 250, -1));

        date_dueDate.setEnabled(false);
        date_dueDate.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        date_dueDate.setFuente(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        date_dueDate.setPlaceholder("Chọn ngày trả");
        panel_main.add(date_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 540, 250, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 204));
        jLabel17.setText("Mã sinh viên");
        panel_main.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 120, -1));

        jLabel18.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 204));
        jLabel18.setText("Ngày mượn");
        panel_main.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, 120, -1));

        submitButton.setBackground(new java.awt.Color(100, 136, 234));
        submitButton.setText("Cho mượn");
        submitButton.setEnabled(false);
        submitButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        panel_main.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 700, 210, -1));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mượn sách");
        jPanel2.add(jLabel3);

        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 350, 50));

        jPanel3.setBackground(new java.awt.Color(100, 136, 234));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thông tin sách");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Mã sách");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, -1));

        lbl_bookId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_bookIdActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 360, 40));

        jLabel21.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tên sách");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, -1));

        lbl_bookName.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lbl_bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_bookNameActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 360, 40));

        jLabel22.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tác giả");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, -1));

        lbl_author.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_authorActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 360, 40));

        lbl_publisher.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_publisherActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 360, 40));

        jLabel23.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nhà xuất bản");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 150, -1));

        jLabel24.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Thể loại");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, -1));

        lbl_category.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_categoryActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 360, 40));

        jLabel25.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Số lượng");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 150, -1));

        lbl_quantity.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_quantityActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 360, 40));

        panel_main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 440, 800));

        lbl_bookError.setForeground(new java.awt.Color(255, 0, 0));
        panel_main.add(lbl_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 290, 240, 20));

        lbl_studetntError.setForeground(new java.awt.Color(255, 0, 0));
        panel_main.add(lbl_studetntError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 190, 240, 20));

        checkButton.setBackground(new java.awt.Color(100, 136, 234));
        checkButton.setText("Kiểm tra");
        checkButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        panel_main.add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 620, 210, -1));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 800));

        setSize(new java.awt.Dimension(1425, 810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_studentIdActionPerformed

    private void lbl_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_studentNameActionPerformed

    private void lbl_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_emailActionPerformed

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    private void txt_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentIdActionPerformed

    private void txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusLost

    }//GEN-LAST:event_txt_bookIdFocusLost

    private void txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusLost

    }//GEN-LAST:event_txt_studentIdFocusLost

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void lbl_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_bookIdActionPerformed

    private void lbl_bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_bookNameActionPerformed

    private void lbl_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_authorActionPerformed

    private void lbl_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_publisherActionPerformed

    private void lbl_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_categoryActionPerformed

    private void comboBoxMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMajorActionPerformed

    private void lbl_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_quantityActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Book book = new Book(lbl_bookId.getText(), lbl_bookName.getText());

        Student student = new Student(Integer.parseInt(lbl_studentId.getText()), lbl_studentName.getText());

        if (issueController.issueBook(book, student, date_issueDate.getDatoFecha(), date_dueDate.getDatoFecha())) {
            JOptionPane.showMessageDialog(this, "Mượn sách thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Mượn sách không thành công");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        if (validateUserInput()) {
            submitButton.setEnabled(true);
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle checkButton;
    private javax.swing.JComboBox<String> comboBoxMajor;
    private rojeru_san.componentes.RSDateChooser date_dueDate;
    private rojeru_san.componentes.RSDateChooser date_issueDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private app.bolivia.swing.JCTextField lbl_author;
    private javax.swing.JLabel lbl_bookError;
    private app.bolivia.swing.JCTextField lbl_bookId;
    private app.bolivia.swing.JCTextField lbl_bookName;
    private app.bolivia.swing.JCTextField lbl_category;
    private app.bolivia.swing.JCTextField lbl_email;
    private app.bolivia.swing.JCTextField lbl_publisher;
    private app.bolivia.swing.JCTextField lbl_quantity;
    private app.bolivia.swing.JCTextField lbl_studentId;
    private app.bolivia.swing.JCTextField lbl_studentName;
    private javax.swing.JLabel lbl_studetntError;
    private javax.swing.JPanel panel_main;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo1;
    private rojerusan.RSMaterialButtonRectangle submitButton;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_studentId;
    // End of variables declaration//GEN-END:variables
}
