/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.BookController;
import controllers.IssueController;
import controllers.StudentController;
import utils.DBConnection;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import models.Book.Book;
import models.Issue.Issue;
import models.Student.Student;

/**
 *
 * @author trinh
 */
public class ReturnBook extends javax.swing.JFrame {

    private IssueController issueController;
    private BookController bookController;
    private StudentController studentController;

    public ReturnBook() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        issueController = new IssueController(this);
        bookController = new BookController(this);
        studentController = new StudentController(this);
    }

    public boolean validateUserInput() {
        try {
            if (txt_studentId.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên");
                return false;
            }

            int id = Integer.parseInt(txt_studentId.getText());
            Student student = studentController.getStudentById(id);
            if (student != null) {
                lbl_studentName.setText(student.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Sinh viên không tồn tại");
                return false;
            }

            if (txt_bookId.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách");
                return false;
            }

            Book book = bookController.getBookById(txt_bookId.getText());
            if (book != null) {
                lbl_bookName.setText(book.getTitle());
            } else {
                JOptionPane.showMessageDialog(this, "Sách không tồn tại");
            }

            if (isAlreadyIssued()) {
                Issue issue = issueController.getByBookIdAndStudentId(book.getId(), student.getId());
                if (issue != null) {
//                    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
//                    String formattedIssueDate = formatter.format(issue.getIssueDate());
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

                    // Format the date as a string
                    String formattedIssueDate = issue.getIssueDate().format(formatter);
                    String formattedDueDate = issue.getDueDate().format(formatter);

                    lbl_issueId.setText(String.valueOf(issue.getId()));
                    lbl_issueDate.setText(formattedIssueDate);
                    lbl_dueDate.setText(formattedDueDate);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bạn chưa mượn quyển sách này");
                return false;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã sinh viên không hợp lệ");
            return false;
        }
        return true;
    }

//    Check if a book is already issued by a student
    public boolean isAlreadyIssued() {
        String bookId = txt_bookId.getText();
        int studentId = Integer.parseInt(txt_studentId.getText());

        if (issueController.getByBookIdAndStudentId(bookId, studentId) != null) {
            return true;
        }

        return false;
    }

    public void clearUserInput() {
        txt_bookId.setText("");
        txt_studentId.setText("");
        lbl_bookName.setText("");
        lbl_studentName.setText("");
        lbl_issueDate.setText("");
        lbl_issueId.setText("");
        lbl_dueDate.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSDateChooserBeanInfo1 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        panel_main = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_bookId = new app.bolivia.swing.JCTextField();
        txt_studentId = new app.bolivia.swing.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        checkButton = new rojerusan.RSMaterialButtonRectangle();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_issueId = new app.bolivia.swing.JCTextField();
        jLabel21 = new javax.swing.JLabel();
        lbl_bookName = new app.bolivia.swing.JCTextField();
        jLabel22 = new javax.swing.JLabel();
        lbl_studentName = new app.bolivia.swing.JCTextField();
        lbl_dueDate = new app.bolivia.swing.JCTextField();
        jLabel23 = new javax.swing.JLabel();
        lbl_bookError1 = new javax.swing.JLabel();
        lbl_bookError = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_issueDate = new app.bolivia.swing.JCTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dangerButton = new rojerusan.RSMaterialButtonRectangle();
        submitButton = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("Mã sách");
        panel_main.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 300, 80, -1));

        txt_bookId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_bookId.setForeground(new java.awt.Color(102, 102, 102));
        txt_bookId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_bookId.setPhColor(new java.awt.Color(102, 102, 102));
        txt_bookId.setPlaceholder("Nhập mã sách");
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 290, 250, 40));

        txt_studentId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_studentId.setForeground(new java.awt.Color(102, 102, 102));
        txt_studentId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_studentId.setPhColor(new java.awt.Color(102, 102, 102));
        txt_studentId.setPlaceholder("Nhập mã sinh viên");
        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusLost(evt);
            }
        });
        txt_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 210, 250, 40));

        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 204));
        jLabel17.setText("Mã sinh viên");
        panel_main.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 220, 120, -1));

        checkButton.setBackground(new java.awt.Color(100, 136, 234));
        checkButton.setText("Kiểm tra");
        checkButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        panel_main.add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 380, 210, -1));

        jPanel3.setBackground(new java.awt.Color(100, 136, 234));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thông tin mượn sách");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Mã phiếu mượn");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));

        lbl_issueId.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jPanel3.add(lbl_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 360, 40));

        jLabel21.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tên sách");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, -1));

        lbl_bookName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_bookNameActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, 40));

        jLabel22.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tên sinh viên");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, -1));

        lbl_studentName.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_studentNameActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 360, 40));

        lbl_dueDate.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_dueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_dueDateActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 360, 40));

        jLabel23.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ngày trả");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 150, -1));

        lbl_bookError1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lbl_bookError1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(lbl_bookError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 360, 110));

        lbl_bookError.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        lbl_bookError.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(lbl_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 360, 60));

        jLabel24.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ngày mượn");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 150, -1));

        lbl_issueDate.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lbl_issueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_issueDateActionPerformed(evt);
            }
        });
        jPanel3.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 360, 40));

        panel_main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 450, 840));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trả sách");
        jPanel1.add(jLabel1);

        panel_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, 350, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/51516_arrow_back_left_icon.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11);

        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        panel_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 90, 700, 700));

        dangerButton.setBackground(new java.awt.Color(255, 0, 0));
        dangerButton.setText("Đã mất");
        dangerButton.setEnabled(false);
        dangerButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        dangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangerButtonActionPerformed(evt);
            }
        });
        panel_main.add(dangerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 210, -1));

        submitButton.setBackground(new java.awt.Color(0, 255, 0));
        submitButton.setText("Hoàn tất");
        submitButton.setEnabled(false);
        submitButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        panel_main.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, 210, -1));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 800));

        setSize(new java.awt.Dimension(1658, 810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    private void txt_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentIdActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        if (validateUserInput()) {
            dangerButton.setEnabled(true);
            submitButton.setEnabled(true);
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    private void txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusLost

    }//GEN-LAST:event_txt_studentIdFocusLost

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void lbl_issueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_issueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_issueDateActionPerformed

    private void lbl_dueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_dueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_dueDateActionPerformed

    private void lbl_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_studentNameActionPerformed

    private void lbl_bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_bookNameActionPerformed

    private void dangerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangerButtonActionPerformed
        try {
            int id = Integer.parseInt(lbl_issueId.getText());
            int studentId = Integer.parseInt(txt_studentId.getText());

            int result = JOptionPane.showConfirmDialog(this, "Xác nhận mất sách", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.OK_OPTION) {
                issueController.returnBook(id, "Đã mất");
                Student student = studentController.getStudentById(studentId);
                student.setIsBanned(1);
                studentController.updateStudent(student);
            }

            clearUserInput();

        } catch (Exception e) {
            // Handle the exception if the date string is not in the expected format
            e.printStackTrace();
        }
    }//GEN-LAST:event_dangerButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Book book = bookController.getBookById(txt_bookId.getText());

        try {
            int id = Integer.parseInt(lbl_issueId.getText());

            String status = "Đã trả";

            Date dueDate = new SimpleDateFormat("dd/MM/yyyy").parse(lbl_dueDate.getText());
            
            int studentId = Integer.parseInt(txt_studentId.getText());

            //          Kiểm tra nếu ngày trả sách lớn hơn hạn trả
            if (dueDate.before(new Date())) {
                status = "Quá hạn";
                JOptionPane.showMessageDialog(this, "Đã quá hạn trả sách");
                Student student = studentController.getStudentById(studentId);
                student.setIsBanned(1);
                studentController.updateStudent(student);
            }

            if (issueController.returnBook(id, status)) {
                JOptionPane.showMessageDialog(this, "Trả sách thành công");

                book.setQuantity(book.getQuantity() + 1);
                bookController.updateBook(book);
                clearUserInput();
            } else {
                JOptionPane.showMessageDialog(this, "Trả sách không thành công");
            }
        } catch (Exception e) {
            // Handle the exception if the date string is not in the expected format
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle checkButton;
    private rojerusan.RSMaterialButtonRectangle dangerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_bookError;
    private javax.swing.JLabel lbl_bookError1;
    private app.bolivia.swing.JCTextField lbl_bookName;
    private app.bolivia.swing.JCTextField lbl_dueDate;
    private app.bolivia.swing.JCTextField lbl_issueDate;
    private app.bolivia.swing.JCTextField lbl_issueId;
    private app.bolivia.swing.JCTextField lbl_studentName;
    private javax.swing.JPanel panel_main;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo1;
    private rojerusan.RSMaterialButtonRectangle submitButton;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_studentId;
    // End of variables declaration//GEN-END:variables
}
